# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: question.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'question.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equestion.proto\"\xe1\x01\n\x08Question\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61uthor_nick\x18\x02 \x01(\t\x12\x14\n\x0csubject_name\x18\x03 \x01(\t\x12\x10\n\x08typename\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x61tabase_id\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x0f\n\x07\x63reated\x18\x07 \x01(\t\x12\x15\n\rthumbnail_url\x18\x08 \x01(\t\x12\x16\n\x0e\x61nswer_content\x18\t \x01(\t\x12\x13\n\x0b\x61nswer_nick\x18\n \x01(\t\x12\x11\n\tanswer_ai\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=19
  _globals['_QUESTION']._serialized_end=244
# @@protoc_insertion_point(module_scope)
